apiVersion: v1
kind: Service
metadata:
  name: myapp1-lb-service
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - name: http
      port: 80          # Service Port (external)
      targetPort: 80    # Container Port (inside Pod)
